# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Adding Default Locations
Location.create(place: "Patna")
Location.create(place: "Muzaffarpur")
Location.create(place: "Gaya")
Location.create(place: "Chapra")
Location.create(place: "Vaishali")
Location.create(place: "Begusarai")
Location.create(place: "Saran")
Location.create(place: "Nawada")
Location.create(place: "Jehanabad")
Location.create(place: "Samastipur")
Location.create(place: "Munger")
Location.create(place: "Siwan")
Location.create(place: "Nalanda")
Location.create(place: "Aurangabad")
Location.create(place: "Darbhanga")
Location.create(place: "Khagaria")
Location.create(place: "Gopalganj")
Location.create(place: "Sheikhpura")
Location.create(place: "Rohtas")
Location.create(place: "Madhubani")
Location.create(place: "Saharsa")
Location.create(place: "Paschimi Champaran")
Location.create(place: "Lakhisarai")
Location.create(place: "Kaimpur")
Location.create(place: "Supaul")
Location.create(place: "Madhepura")
Location.create(place: "Purbi Champaran")
Location.create(place: "Jamui")
Location.create(place: "Buxar")
Location.create(place: "Araria")
Location.create(place: "Purnia")
Location.create(place: "Sheohar")
Location.create(place: "Banka")
Location.create(place: "Bhojpur")
Location.create(place: "Kishanganj")
Location.create(place: "Katihar")
Location.create(place: "Sitamarhi")
Location.create(place: "Bhagalpur")
